name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  shared_preferences: ^2.2.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  meta: ^1.11.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/foods.json
    - assets/images/

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani.ttf
        - asset: assets/fonts/Rajdhani-Medium.ttf
