// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUBvk-Xy7Bwj9XOmTPC2GwSb0d1r7lAxk',
    appId: '1:423477202439:web:92a3532b94e2837dad24a2',
    messagingSenderId: '423477202439',
    projectId: 'finalproject-755',
    authDomain: 'finalproject-755.firebaseapp.com',
    storageBucket: 'finalproject-755.appspot.com',
    measurementId: 'G-XEX2LMJNV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF5jzdaqCgg5s1KBaQ_DWd292Nh4C-nnA',
    appId: '1:423477202439:android:43a8b851964fd3e3ad24a2',
    messagingSenderId: '423477202439',
    projectId: 'finalproject-755',
    storageBucket: 'finalproject-755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6G2NxMkND0YLvE7kGjC-awDKzq-l5sHQ',
    appId: '1:423477202439:ios:e88b09717306dd23ad24a2',
    messagingSenderId: '423477202439',
    projectId: 'finalproject-755',
    storageBucket: 'finalproject-755.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6G2NxMkND0YLvE7kGjC-awDKzq-l5sHQ',
    appId: '1:423477202439:ios:e88b09717306dd23ad24a2',
    messagingSenderId: '423477202439',
    projectId: 'finalproject-755',
    storageBucket: 'finalproject-755.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUBvk-Xy7Bwj9XOmTPC2GwSb0d1r7lAxk',
    appId: '1:423477202439:web:b3ebbd1e65a102b0ad24a2',
    messagingSenderId: '423477202439',
    projectId: 'finalproject-755',
    authDomain: 'finalproject-755.firebaseapp.com',
    storageBucket: 'finalproject-755.appspot.com',
    measurementId: 'G-E7F3HLJR1N',
  );

}